### ISSUE TITLE
Failure to Precompile HTTP Due To Missing cert.pem File

### ISSUE THREAD

**Issue by umbriquse** [JuliaWeb/HTTP.jl#887]
- Julia 1.7.2
 - HTTP.jl 1.2.0
 - MbedTLS.jl 1.1.0
 
I'm getting an error when trying to compile `HTTP`. I looked in the "/usr/share/julia/" and did not find any sort of `.pem` file. I'm not certain if this is some sort of issue on my end, or if this is actually a bug.

```julia
Failed to precompile HTTP [cd3eb016-35fb-5094-929b-558a96fad6f3] to /home/jlehto/.julia/compiled/v1.7/HTTP/jl_NPmoqn.
ERROR: LoadError: InitError: SystemError: opening file "/usr/share/julia/cert.pem": No such file or directory
Stacktrace:
 [1] open
   @ ./io.jl:328 [inlined]
 [2] read(filename::String, #unused#::Type{String})
   @ Base ./io.jl:436
 [3] __sslinit__()
   @ MbedTLS ~/.julia/packages/MbedTLS/qUI5E/src/ssl.jl:785
 [4] __init__()
   @ MbedTLS ~/.julia/packages/MbedTLS/qUI5E/src/MbedTLS.jl:55
 [5] include(x::String)
   @ HTTP ~/.julia/packages/HTTP/XJG1J/src/HTTP.jl:1
 [6] top-level scope
   @ ~/.julia/packages/HTTP/XJG1J/src/HTTP.jl:31
 [7] top-level scope (repeats 2 times)
   @ none:1
during initialization of module MbedTLS
```

VERSION INFO:
```julia
julia> versioninfo()
Julia Version 1.7.2
Commit bf53498635* (2022-02-06 15:21 UTC)
Platform Info:
  OS: Linux (x86_64-pc-linux-gnu)
  CPU: AMD Ryzen Threadripper 3990X 64-Core Processor
  WORD_SIZE: 64
  LIBM: libopenlibm
  LLVM: libLLVM-13.0.1 (ORCJIT, znver2)
```

PACKAGE VERSION:
```julia
julia> Pkg.status("HTTP")
  [cd3eb016] HTTP v1.2.0
```

**Comment by fredrikekre** [comment]
How did you install Julia? See https://github.com/JuliaLang/MbedTLS.jl/pull/238#issuecomment-1178170566

**Comment by umbriquse** [comment]
I downloaded the `.tar` file from the official website

**Comment by umbriquse** [comment]
Following the links, it seems that downloading [arch linux julia file](https://aur.archlinux.org/packages/julia-bin) will do the trick.

**Comment by Barlerer** [comment]
I have the same issue. And I have installed from Conda (In a clean, new environment).
I only have the option of using Conda, what can I do to solve this issue?

**Comment by fredrikekre** [comment]
> Following the links, it seems that downloading [arch linux julia file](https://aur.archlinux.org/packages/julia-bin) will do the trick.

AFAIK that downloads the binary from julialang.org, so perhaps you didn't run that binary when you said 
> I downloaded the .tar file from the official website

?
> I have the same issue. And I have installed from Conda (In a clean, new environment).
I only have the option of using Conda, what can I do to solve this issue?

This should be fixed by https://github.com/JuliaLang/MbedTLS.jl/pull/246 (included in MbedTLS.jl 1.1.1). Otherwise, complain at Conda.

**Comment by umbriquse** [comment]
No I didn't run the binary. I just untarred the provided tar file. Regardless, after updating to 1.7.3 the issue no longer persisted. So either this PR you mentioned fixed it or the 1.7.3 update fixed it.

**Comment by umbriquse** [comment]
I came across the same issue again...

I attempted to resolve the issue by uninstalling julia, and reinstalling using the package manager: `pacman` (I'm using Manjaro). This did not solve the issue. I eventually copied the [cacert file](https://github.com/JuliaLang/MbedTLS.jl/blob/master/src/cacert.pem), and created the `/usr/share/julia/cert.pem` by hand which did solve the issue. Would this be an issue with the binary I used to install Julia, and does this file need to be updated at all in the future?

VERSION INFO:
```julia
Julia Version 1.7.3
Commit 742b9abb4d* (2022-05-06 12:58 UTC)
Platform Info:
  OS: Linux (x86_64-pc-linux-gnu)
  CPU: AMD Ryzen Threadripper 3990X 64-Core Processor
  WORD_SIZE: 64
  LIBM: libopenlibm
  LLVM: libLLVM-14.0.5 (ORCJIT, znver2)
```

**Comment by HenriLaurie** [comment]
Also struggling with 'cert.pem'. The only .pem file I find is

/usr/share/julia/stdlib/v1.7/LibGit2/test/bad_ca_roots.pem

verstioninfo returns:

Julia Version 1.7.3
Commit 742b9abb4d* (2022-05-06 12:58 UTC)
Platform Info:
  OS: Linux (x86_64-pc-linux-gnu)
  CPU: AMD Ryzen 7 4800H with Radeon Graphics
  WORD_SIZE: 64
  LIBM: libopenlibm
  LLVM: libLLVM-14.0.6 (ORCJIT, znver2)

and I am using Manjaro:
DISTRIB_ID=ManjaroLinux
DISTRIB_RELEASE=21.3.7
DISTRIB_CODENAME=Ruah
DISTRIB_DESCRIPTION="Manjaro Linux"

Started happening when I upgraded from Julia v1.7.1 to v1.7.3 today

**Comment by ngmaclaren** [comment]
> I came across the same issue again...
> 
> I attempted to resolve the issue by uninstalling julia, and reinstalling using the package manager: `pacman` (I'm using Manjaro). This did not solve the issue. I eventually copied the [cacert file](https://github.com/JuliaLang/MbedTLS.jl/blob/master/src/cacert.pem), and created the `/usr/share/julia/cert.pem` by hand which did solve the issue. Would this be an issue with the binary I used to install Julia, and does this file need to be updated at all in the future?
> 
> VERSION INFO:
> 
> ```julia
> Julia Version 1.7.3
> Commit 742b9abb4d* (2022-05-06 12:58 UTC)
> Platform Info:
>   OS: Linux (x86_64-pc-linux-gnu)
>   CPU: AMD Ryzen Threadripper 3990X 64-Core Processor
>   WORD_SIZE: 64
>   LIBM: libopenlibm
>   LLVM: libLLVM-14.0.5 (ORCJIT, znver2)
> ```

I had the same issue and this solution worked for me.

**Comment by HenriLaurie** [comment]
Me too! (on upgrading to1.8).

The solution remains as before: do not install the official Manjaro version, instead use the binary from AUR. May be a Manjaro issue rather than a Julia issue. In any case, no fiddling with certs needed.

**Comment by lsh-0** [comment]
@HenriLaurie's advice applies to the official Arch version as well, remove `julia`, install `julia-bin` from AUR and `add HTTP` now installs without issue. Fine work [julia-bin AUR](https://aur.archlinux.org/packages/julia-bin) guys, cheers.

**Comment by dimpase** [comment]
I see the same issue on Gentoo - compiled from source. 

Could please someone explain the root cause here, not "install a binary from somewhere", please?

Why one would expect a cert file shipped by Julia? It's something best left to the OS, IMHO.
